from .orders.consultations import Consultations	    
from .orders.diagnoses import Diagnoses
from .orders.doctors import Doctors
from .orders.hospitals import Hospitals
from .orders.medications import Medications
from .orders.patient_diagnoses import PatientDiagnoses
from .orders.patient_medications import PatientMedications
from .orders.patients import Patients
from .orders.patient_trackers import PatientTrackers
from .orders.trackers import Trackers
