COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://admin:admin123@database-1.cvkc4s8ketvv.eu-north-1.rds.amazonaws.com:3306/lab4'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://admin:admin123@database-1.cvkc4s8ketvv.eu-north-1.rds.amazonaws.com:3306/lab4'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: admin
  MYSQL_ROOT_PASSWORD: admin123
