COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: null

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: null

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: null
  MYSQL_ROOT_PASSWORD: null
